# services:
#   axonbank1:
#     image: axonframework/axonbank
#     depends_on:
#       db:
#         condition: service_healthy
#       rabbitmq:
#         condition: service_started
#       zipkin:
#         condition: service_started
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/axonbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=root
#       - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
#     ports:
#       - "8080:8080"
#   axonbank2:
#     image: axonframework/axonbank
#     depends_on:
#       db:
#         condition: service_healthy
#       rabbitmq:
#         condition: service_started
#       zipkin:
#         condition: service_started
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/axonbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=root
#       - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
#     ports:
#       - "8081:8080"
services:
  axonbank1:
    image: axonframework/axonbank
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
    environment:
      - SPRING_APPLICATION_NAME=Axon Bank Instance1
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/axonbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
    ports:
      - "8080:8080"
  axonbank2:
    image: axonframework/axonbank
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
    environment:
      - SPRING_APPLICATION_NAME=Axon Bank Instance2
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/axonbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
    ports:
      - "8081:8080"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=axonbank
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  rabbitmq:
    build: docker/rabbitmq/
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"